-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 15:55:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pcelmedic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pcelmedic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pcelmedic` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pcelmedic` ;

-- -----------------------------------------------------
-- Table `pcelmedic`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcelmedic`.`cliente` (
  `cedula` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `celular` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cedula`),
  INDEX `idx_cliente_cedula` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pcelmedic`.`dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcelmedic`.`dispositivo` (
  `id_dispositivo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `tipo_reparacion` VARCHAR(100) NOT NULL,
  `tipo_contrasena` VARCHAR(15) NOT NULL,
  `contrasena` VARCHAR(40) NULL DEFAULT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  `id_cliente` VARCHAR(20) NOT NULL,
  `version` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_dispositivo`),
  INDEX `idx_dispositivo_id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `idx_dispositivo_tipo_reparacion` (`tipo_reparacion` ASC) VISIBLE,
  INDEX `idx_dispositivo_marca` (`marca` ASC) VISIBLE,
  CONSTRAINT `dispositivo_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `pcelmedic`.`cliente` (`cedula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pcelmedic`.`reparacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcelmedic`.`reparacion` (
  `id_reparacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` DATETIME NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `costo_repuesto` DECIMAL(10,2) NULL DEFAULT NULL,
  `precio_reparacion` DECIMAL(10,2) NULL DEFAULT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  `id_dispositivo` INT NOT NULL,
  PRIMARY KEY (`id_reparacion`),
  INDEX `idx_reparacion_dispositivo` (`id_dispositivo` ASC) VISIBLE,
  INDEX `idx_reparacion_id_reparacion` (`id_reparacion` ASC) VISIBLE,
  INDEX `idx_reparacion_estado` (`estado` ASC) VISIBLE,
  INDEX `idx_reparacion_fecha_ingreso` (`fecha_ingreso` ASC) VISIBLE,
  CONSTRAINT `reparacion_ibfk_1`
    FOREIGN KEY (`id_dispositivo`)
    REFERENCES `pcelmedic`.`dispositivo` (`id_dispositivo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pcelmedic`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcelmedic`.`factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `id_reparacion` INT NOT NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `idx_factura_id_reparacion` (`id_reparacion` ASC) VISIBLE,
  INDEX `idx_factura_fecha` (`fecha` ASC) VISIBLE,
  INDEX `idx_factura_total` (`total` ASC) VISIBLE,
  CONSTRAINT `factura_ibfk_1`
    FOREIGN KEY (`id_reparacion`)
    REFERENCES `pcelmedic`.`reparacion` (`id_reparacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pcelmedic`.`garantia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcelmedic`.`garantia` (
  `id_garantia` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(20) NOT NULL,
  `observaciones` TEXT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  `id_reparacion` INT NOT NULL,
  `precio_insumos` DECIMAL(10,2) NULL DEFAULT NULL,
  `comentarios_finales` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_garantia`),
  INDEX `idx_garantia_id_reparacion` (`id_reparacion` ASC) VISIBLE,
  INDEX `idx_garantia_fecha_inicio` (`fecha_inicio` ASC) VISIBLE,
  INDEX `idx_garantia_fecha_fin` (`fecha_fin` ASC) VISIBLE,
  CONSTRAINT `garantia_ibfk_1`
    FOREIGN KEY (`id_reparacion`)
    REFERENCES `pcelmedic`.`reparacion` (`id_reparacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
